# Generated by Django 5.2 on 2025-04-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_user_phone_user_display_name_user_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keywords',
        ),
    ]
